// Signs release builds with the owner's own keystore instead of the debug key.
//
// `android/` is generated by `expo prebuild` and never hand-edited, so the signing wiring lives here and is
// re-applied on every prebuild. Credentials come from `mobile/credentials/signing.properties` (git-ignored):
//
//   storeFile=spice-erp-release.jks      (relative to mobile/credentials/)
//   storePassword=…
//   keyAlias=…
//   keyPassword=…
//
// Without that file the release build falls back to the debug key (installable, but not for distribution).
const { withAppBuildGradle } = require('expo/config-plugins')

const MARKER = 'spiceReleaseSigning'

module.exports = function withReleaseSigning(config) {
  return withAppBuildGradle(config, (cfg) => {
    let g = cfg.modResults.contents
    if (g.includes(MARKER)) return cfg

    const loader = `
// ${MARKER}: release keystore from mobile/credentials/signing.properties (git-ignored)
def spiceSigningFile = rootProject.file('../credentials/signing.properties')
def spiceSigning = new Properties()
if (spiceSigningFile.exists()) {
    spiceSigningFile.withInputStream { spiceSigning.load(it) }
}
def spiceHasReleaseKey = spiceSigning.getProperty('storeFile') != null
`
    // top-level, before the android { } block
    g = g.replace(/\nandroid \{/, `${loader}\nandroid {`)

    g = g.replace(
      /signingConfigs \{\n/,
      `signingConfigs {
        release {
            if (spiceHasReleaseKey) {
                storeFile rootProject.file('../credentials/' + spiceSigning.getProperty('storeFile'))
                storePassword spiceSigning.getProperty('storePassword')
                keyAlias spiceSigning.getProperty('keyAlias')
                keyPassword spiceSigning.getProperty('keyPassword')
            }
        }
`
    )

    g = g.replace(
      /(release \{\n(?:\s*\/\/.*\n)*\s*)signingConfig signingConfigs\.debug/,
      `$1signingConfig spiceHasReleaseKey ? signingConfigs.release : signingConfigs.debug`
    )

    cfg.modResults.contents = g
    return cfg
  })
}
